### ISSUE TITLE
beacon(ibeacon) on Android

### ISSUE THREAD

**Issue by godgunman** [godgunman/tii#2]
To see http://altbeacon.github.io/android-beacon-library/samples.html

**Comment by godgunman** [comment]
- library: http://altbeacon.github.io/android-beacon-library/samples.html
- sample of org.altbeacon:android-beacon-library: https://github.com/edina/android-ibeacon-prototype
- sample of org.altbeacon:android-beacon-library: https://github.com/justinodwyer/Beacon-Scanner-and-Logger

**Comment by godgunman** [comment]
https://www.pubnub.com/blog/2015-04-14-building-android-beacon-android-ibeacon-tutorial-overview/

**Comment by telgniw** [comment]
Add a beacon parser.
http://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconParser.html#setBeaconLayout(java.lang.String)

**Comment by telgniw** [comment]
https://en.wikipedia.org/wiki/IBeacon#Ranging

An iOS device receiving an iBeacon transmission can approximate the distance from the iBeacon. The distance (between transmitting iBeacon and receiving device) is categorized into 3 distinct ranges:[14]
- Immediate: Within a few centimeters
- Near: Within a couple of meters
- Far: Greater than 10 meters away
  The maximum range of an iBeacon transmission will depend on the location and placement, obstructions in the environment and where the device is being stored (e.g. in a leather handbag or with a thick case). Standard beacons have an approximate range of 70 meters. Long range beacons can reach up to 450 meters.
